name: Backend Tests   

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./api

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js with caching
        if: github.event_name != 'pull_request'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './api/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Enforce formatting with Prettier
        run: npm run format
    
      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

      - name: Check for outdated packages
        run: npm outdated || echo "No outdated packages found"

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high
