name: Backend Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js with caching
        if: github.event_name != 'pull_request'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Enforce formatting with Prettier
        run: npx prettier --write .

      - name: Run ESLint
        run: npx eslint . --fix

      - name: Run bot to check for errors
        env:
          CI_TEST: true
        run: |
          node index.js &
          sleep 10
          pkill -f "node index.js"

      - name: Verify no runtime errors
        run: echo "Bot started successfully without errors"
      
      - name: Check for outdated packages
        run: npm outdated || echo "No outdated packages found"

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high
